name: Terraform Docs

on:
  pull_request:
    branches:
      - main
    paths:
      - "modules/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform-docs:
    uses: AutomationDojo/reusable-cicd/.github/workflows/terraform-docs.yml@main
    with:
      modules-path: modules
